name: Bewegungssinn
favicon: null
layout_spectrum: 0.49874
typography_spectrum: 0.61188
title: 'Praxis für Rolfing® Strukturelle & Movement Integration'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#00437a'
    - '#0098d4'
    - '#572f08'
    - '#a7bed1'
  brandStrength: 0
  lightness: 0.8783680952619761
  saturation: 0.8314805750269443
  rhythmicContrast: 0.5857982856687158
purpose: []
