name: Bewegungssinn
favicon: null
layout_spectrum: 0.17642
typography_spectrum: 0.1569
title: 'Praxis für Rolfing® Strukturelle & Movement Integration'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#00437a'
    - '#0098d4'
    - '#572f08'
    - '#a7bed1'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
