title: 'Praxis für Rolfing® Strukturelle & Movement Integration'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3727598
  brandStrength: 0.1989247
  lightness: 0.8125
  brandColors:
    - '#ffffff'
    - '#00437a'
    - '#0098d4'
    - '#572f08'
    - '#a7bed1'
  rhythmicContrast: 0.3494624
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Bewegungssinn
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.1569
layout_spectrum: 0.4103943
